### ISSUE TITLE
Better documentation of the boards supported by urboot

### ISSUE THREAD

**Issue by mcuee** [stefanrueger/urboot#13]
There are quite some boards with urboot support out of the box in this repo. It is great to see that the popular Uno board and Pro Mini are supported. It is good to provide simple documentation of the other boards supported out of box.

Example:
https://github.com/stefanrueger/urboot/tree/main/bootloaders/board_uno (Arduino Uno or clones)
https://github.com/stefanrueger/urboot/tree/main/bootloaders/board_promini (Arduino Pro Mini and clones)
https://github.com/stefanrueger/urboot/tree/main/bootloaders/board_digispark-pro (ATtiny167 based)
https://github.com/stefanrueger/urboot/tree/main/bootloaders/board_digispark (ATtiny85 based)
https://github.com/stefanrueger/urboot/tree/main/bootloaders/board_mega-r3 (Is this Arduino Mega2560?)

**Comment by stefanrueger** [comment]
Good idea: done in the readme file
