### ISSUE TITLE
Docker container to be able to build urboot

### ISSUE THREAD

**Issue by mcuee** [stefanrueger/urboot#15]
It may be a good idea to create github action CI for urboot, probably just for Linux as the toolchain in the repo is only for Linux.

One possibility is to use Docker container in the CI.

**Comment by stefanrueger** [comment]
The urboot project only works under Linux and can easily be "checked" by executing `make all`, which generates a variety of bootloaders. So, CI is less of an issue for this project. I would like to provide a working docker container for the ability to `make` bootloaders in other environments (eg, Mac, Windows) but lack the drive, skills and test beds (Macs, Windows) to do so.

**Comment by mcuee** [comment]
Docker container will be good. I do not know much but if you come out with the Docker Compose file, I should be able to carry out the test under Mac and Windows.
