### ISSUE TITLE
URBoot is too fast, making manual reset more difficult...

### ISSUE THREAD

**Issue by WestfW** [stefanrueger/urboot#28]
https://forum.arduino.cc/t/minicore-atmega328-bootloader-burning-issue/1190856/11

Perhaps the default WDT timeout should be 1s rather than 500ms

**Comment by stefanrueger** [comment]
Although the C source has a default of 500 ms, the accompanying `Makefile` overrides, by default, the timeout to be 1 s. The precompiled bootloaders from the [`urboot.hex` repository](https://github.com/stefanrueger/urboot.hex/tree/main) give a [choice of 1 s or 2 s timeout when branching](https://github.com/stefanrueger/urboot.hex/tree/main/cores/minicore/atmega328pb)  to the desired bootloader.

It is unlikely that a user creates a bootloader by compiling the C source from the command line (though they can): it is recommended to use the Makefile, which invokes a gcc-wrapper to carry out proper positioning of the bootloader sections.
