### ISSUE TITLE
To add autobaud support

### ISSUE THREAD

**Issue by mcuee** [stefanrueger/urboot#3]
It will be good to add autoboot support as a potential enhancement.
* https://github.com/avrdudes/avrdude/pull/1171#issuecomment-1310240898

> It makes things simpler not just for users, but developers too. 
> Autobaud is also useful for older parts with RC oscillators that weren't well-tuned from the factory.

**Comment by stefanrueger** [comment]
Done. :)

**Comment by DRSDavidSoft** [comment]
@stefanrueger Sorry to bother you, I was wondering, how would this excellent feature even work? Can you please add some explanation to the great documentation you've written?

https://github.com/stefanrueger/urboot/blob/main/urprotocol.md

Thanks for all the work you do! 🤝
